### ISSUE TITLE
I'm not getting good metrics

### ISSUE THREAD

**Issue by jcarles** [andreineculai/MPC#3]
hello,
I'm training the MPC model and I'm not getting loss above 33. with 1600 epochs. 
I'm also having bad metrics values. Sure I'm missing something. I have downloaded the files 'captions_train2017' and 'instances_train2017' from the COCO website and put them into the datasets/coco folder. And also I have downloaded the train2017.zip file from COCO website, decompressed it and put the path in config file.
I have setup resources/config/probabilistic.yml with paths but I have not changed any other hyperparameter. I have left the default values.
I have created the conda environment and run:
python code/main.py --config_name=probabilistic.yaml --mode=train

You can see the values and metrics in the file uploaded:

[train2.txt](https://github.com/andreineculai/MPC/files/9963619/train2.txt)

What I'm missing?

Any help? I would appreciate any idea, 

thank you

**Comment by MaxwellZYD** [comment]
> hello, I'm training the MPC model and I'm not getting loss above 33. with 1600 epochs. I'm also having bad metrics values. Sure I'm missing something. I have downloaded the files 'captions_train2017' and 'instances_train2017' from the COCO website and put them into the datasets/coco folder. And also I have downloaded the train2017.zip file from COCO website, decompressed it and put the path in config file. I have setup resources/config/probabilistic.yml with paths but I have not changed any other hyperparameter. I have left the default values. I have created the conda environment and run: python code/main.py --config_name=probabilistic.yaml --mode=train
> 
> You can see the values and metrics in the file uploaded:
> 
> [train2.txt](https://github.com/andreineculai/MPC/files/9963619/train2.txt)
> 
> What I'm missing?
> 
> Any help? I would appreciate any idea,
> 
> thank you

Have you ever had this problem in training?

Training for epoch 0:   0%|                                                                                                                                         | 0/31 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    fire.Fire(main)
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 33, in main
    trainer.train()
  File "/home/jsj_20_01/mpc/MPC-main/code/trainers/trainer_probabilistic.py", line 117, in train
    for data in tqdm(self.train_dataloader, desc='Training for epoch ' + str(epoch)):
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/anaconda3/envs/zyd/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jsj_20_01/mpc/MPC-main/code/datasets/coco_dataset.py", line 156, in __getitem__
    'image': [self.retrieve_modality('image', id, cat) for id, cat in zip(ids, cats)],
  File "/home/jsj_20_01/mpc/MPC-main/code/datasets/coco_dataset.py", line 156, in <listcomp>
    'image': [self.retrieve_modality('image', id, cat) for id, cat in zip(ids, cats)],
  File "/home/jsj_20_01/mpc/MPC-main/code/datasets/coco_dataset.py", line 110, in retrieve_modality
    return self.get_img_for_id_and_cat(id, cat)
  File "/home/jsj_20_01/mpc/MPC-main/code/datasets/coco_dataset.py", line 116, in get_img_for_id_and_cat
    with open(img_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_coco_dataset>/images/train2017/000000543840.jpg'

**Comment by joancarlesbadia** [comment]
It seems that you have not set the image_root in the configuration file.
Have you download the coco images dataset? If you have downloaded it, you have to setup the /code/resources/configs/probabilistic.yaml or deterministic.yaml and set the path where you have downloaded the images in the images_route

**Comment by MaxwellZYD** [comment]
> 


Thank you very much for your answer. I have downloaded the dataset and configured the path and file address. But my feeling is more like the data itself.
